plugins {
    id 'com.android.application'
}
android {
    namespace 'com.seoul.metersim'
    compileSdk 34
    defaultConfig {
        applicationId "com.seoul.metersim"
        minSdk 26
        targetSdk 34
        versionCode 10
        versionName "1.0"
    }
    buildTypes {
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation 'com.github.mik3y:usb-serial-for-android:3.7.2'
}
